core/core/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ticketing.urls'))
]

core/ticketing/urls.py
from django.urls import path, include
from . import views
app_name = "ticketing"
urlpatterns = [
    path("create_ticket/", views.Post_Ticket_View.as_view(),name = "create_ticket"),
    path("show_all_tickets/", views.show_all_tickets_TemplateView.as_view(), name="show_all_tickets"),
    path("ticket_detail/<int:ticket_id>/", views.ticket_detail_TemplateView.as_view(), name= "ticket_detail"),
    # path("reply_on_ticket/<int:ticket_id>", views.reply_on_ticket.as_view(), name= "reply_on_ticket"),

]

core/templates/PostTicket.html
{% extends 'base.html' %}

{% block content %}
  <h1>Enter Data</h1>
  {% if error_message %}
    <p>{{ error_message }}</p>
  {% endif %}
  {% if success_message %}
    <p>{{ success_message }}</p>
  {% endif %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Data</button>
  </form>
{% endblock %}

core/templates/base.html
<!doctype <!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>HelpicalTicketing</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        
        {% block content %}
        {% endblock content %}
        
    </body>
</html>>

core/templates/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Enter Data</h1>
  {% if error_message %}
    <p>{{ error_message }}</p>
  {% endif %}
  {% if success_message %}
    <p>{{ success_message }}</p>
  {% endif %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Data</button>
  </form>
{% endblock %}

core/templates/show_tickets.html
{% extends "base.html" %}

{% block content %}

  <h1>All Tickets</h1>
  
  <!-- link to create a new ticket -->
  <a href="{% url 'ticketing:create_ticket' %}">Create a new ticket</a>
  
  <!-- check if there are any tickets -->
  {% if tickets %}
  
    <!-- display each ticket -->
    <ul>
    {% for ticket in tickets %}
      <li>
        <h2>{{ ticket.title }}</h2>
        <p>{{ ticket.target_user_name }}</p>
        <a href="{% url 'ticketing:ticket_detail' ticket.ticket_id %}">View details</a>
        <!-- add more ticket information as needed -->
      </li>
    {% endfor %}
    </ul>
    
  {% else %}
  
    <!-- display message if there are no tickets -->
    <p>There are no tickets to display.</p>
    
  {% endif %}

{% endblock %}

core/templates/ticket_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Ticket #{{ ticket_details.content_id }} - {{ ticket_details.message }}</h1>
  {% comment %} <p>{{ ticket_details.content }}</p> {% endcomment %}
  
  <!-- display ticket replies, if any -->
  {% comment %} {% if ticket_details.replies %} {% endcomment %}
    <h2>Replies:</h2>
    
    {% for reply in ticket_details.content %}
      <div class="ticket-reply">
        <p class="reply-content">{{ reply.message }}</p>
      </div>
    {% endfor %}
  
  <!-- provide a form to add a new reply -->
  <h2>Add a reply:</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}